In [ ]:
import numpy as np

In [ ]:
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]]).T
print("La forma de X es", X.shape)
Y = np.array([1, 1, -1, -1]).reshape(-1, 1)
print("La forma de Y es", Y.shape)
W = np.array([0, 0, 0]).reshape(-1, 1).T
print("La forma de W es", W.shape)
Waux = np.array([1, 1, 1]).reshape(-1, 1).T
lr = 0.1

print("\nIteraciones:")
while (W != Waux).any():
  Waux = W
  for j in range(Y.shape[0]):
    v = np.dot(W, X[:,j].reshape(-1,1))
    y = np.sign(v)
    e = lr * (Y[j] - y)
    W = W + e * X[:,j].reshape(-1,1).T
    #print("X:", X[:,j].reshape(-1,1))
    #print("Label:",Y[j],". Output:", y,". Error:", e)
    print(W)
  print("\n")

La forma de X es (3, 4)
La forma de Y es (4, 1)
La forma de W es (1, 3)

Iteraciones:
[[0.  0.  0.1]]
[[0.  0.  0.1]]
[[-0.2  0.  -0.1]]
[[-0.2  0.  -0.1]]


[[-0.2  0.   0.1]]
[[-0.2  0.   0.1]]
[[-0.2  0.   0.1]]
[[-0.2  0.   0.1]]


[[-0.2  0.   0.1]]
[[-0.2  0.   0.1]]
[[-0.2  0.   0.1]]
[[-0.2  0.   0.1]]


